spring.application.name=UISP

spring.datasource.url=jdbc:postgresql://localhost:5432/uisp
spring.datasource.username=postgres
spring.datasource.password=thangdeptrai123
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#Jwt
uisp.jwt.base64-secret=LVIe88d1bftZTX8Ykz7TTUd6cR5Q6qL0o0ivPrbot2GBX2YBw9pT2CgGus2aXhHmRYl4NfdMDI7G/hYxBxw33A==
uisp.jwt.access-token-validity-in-seconds=90000
uisp.jwt.refresh-token-validity-in-seconds=90000

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=xamthang09@gmail.com
spring.mail.password=enotqwjnuyphtfzd
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.data.redis.host=host
spring.data.redis.port=6379

